name: Main
on: push

jobs:
  win32:
    runs-on: windows-latest
    steps:
      - name: Variables
        id: vars
        run: |
          echo "::group::sdk"
          cd $HOME && mkdir sdk && cd sdk
          echo "::set-output name=sdk::$PWD"
          echo "::endgroup::"
          echo "::group::tip"
          curl -f -s -L -o HEAD.json 'https://go.googlesource.com/go/+/refs/heads/master?format=JSON'
          cat HEAD.json
          echo "::endgroup::"

      - run: |
          echo ${{ steps.vars.outputs.sdk }}
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: tie/github-actions-test@master
        with:
          name: world
      - run: |
          echo Running on ${{ runner.os }}
