name: Main
on: push

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: tie/github-actions-test@master
        with:
          name: world
      - run: |
          echo Running on ${{ runner.os }}
