name: Main
on: push

jobs:
  win32:
    runs-on: windows-latest
    steps:
      - name: Variables
        id: vars
        run: |
          echo "::group::sdk"
          cd $HOME && mkdir sdk && cd sdk
          echo "::set-output name=sdk::$PWD"
          echo "::endgroup::"
          echo "::group::tip"
          curl -fsL -o HEAD.json 'https://go.googlesource.com/go/+/refs/heads/master?format=JSON'
          awk '/"commit"/{print substr($2,2,40);exit}' HEAD.json >HEAD
          echo "::set-output name=tip::$(cat HEAD)"
          echo "::endgroup::"

      - name: Print
        run: |
          echo ${{ steps.vars.outputs.tip }}
          echo ${{ steps.vars.outputs.sdk }}
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: tie/github-actions-test@master
        with:
          name: world
      - run: |
          echo Running on ${{ runner.os }}
