name: Main
on: push

jobs:
  win32:
    runs-on: windows-latest
    steps:
      - run: |
          echo Running on ${{ runner.os }}
          cd
          mkdir sdk
          cd sdk
          pwd
          touch yay
          echo $HOME/sdk
          ls $HOME/sdk
        #shell: bash
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: tie/github-actions-test@master
        with:
          name: world
      - run: |
          echo Running on ${{ runner.os }}
