name: Main
on: push

jobs:
  win32:
    runs-on: windows-latest
    steps:
      - id: vars
        run: |
          echo Running on ${{ runner.os }}
          echo "::group::Output"
          cd $HOME
          mkdir sdk
          cd sdk
          echo "::set-output name=sdk::$PWD"
          echo "::endgroup::"
      - run: |
          echo ${{ steps.vars.outputs.sdk }}
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: tie/github-actions-test@master
        with:
          name: world
      - run: |
          echo Running on ${{ runner.os }}
